---
title: "第2章"
format: html
editor: visual
# 以下設定追加
number-sections: true
toc: true
toc-depth: 3
toc-location: left
theme: spacelab
code-fold: show #code-fold:showでコードの折り畳みが可能
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, fig.align = "center")
library(foreach)
library(magrittr)
library(ggplot2)
library(kableExtra)
library(CausalInferenceTextbook)
color_main <- scales::viridis_pal(option = "C")(1)
```

# フィッシャーのp値

参照：[因果推論の計量経済学（川口、澤田）：第2章　無作為化実験](https://github.com/keisemi/EconometriciansGuide_CausalInference/blob/main/main/randomization_fisher_pvalue.html)

## 定数とパラメータの設定

```{r}
set.seed(1)
N <- 1000 　#個体数
R <- 1000   #モンテカルロのドロー数
N_1 <- 500　#処置群のサイズ

tau_population <- 0.2 #母集団における平均処置効果
```

## データの生成

```{r}
outcome_potential <- 
  tibble::tibble(
    y_0 = rnorm(N, mean = 0, sd = 1),
    y_1 = rnorm(N, mean = tau_population, sd = 1)
  )

tau <- outcome_potential |> 
  dplyr::summarise(
    tau = mean(y_1 - y_0)
  ) |> 
  dplyr::pull(tau)

outcome_potential |> 
  head() |> 
  kableExtra::kbl() |> 
  kableExtra::kable_styling()

outcome_potential |> 
  modelsummary::datasummary_skim()

# サンプルにおける平均処置効果
tau

# 観測データ（顕在結果）の生成
data_realized <- 
  generate_data_randomized(
    outcome_potential = outcome_potential,
    N_1 = N_1,
    seed = 1
  )

data_realized |> 
  head() |> 
  kbl() |> 
  kable_styling()

data_realized |> 
  modelsummary::datasummary_skim()
```


## 分析と推定
```{r}
t <- 
  calculate_difference_in_means(
    data_realized = data_realized
    )
t
```

```{r}
outcome_potential_null <- 
  data_realized |> 
  dplyr::mutate(
    y_0 = y,
    y_1 = y
  )

t_distribution <- 
  1:R %>%
  purrr::map(
    .,
    ~ generate_data_randomized(
        outcome_potential = outcome_potential_null,
        N_1 = N_1,
        seed = .
        ) |> 
      calculate_difference_in_means()
  ) |> 
  purrr::reduce(c) #purrr::reduce(c)でリストを1つのベクトルに統合

pvalue <- 
 mean(abs(t_distribution) > abs(t)) 

format(pvalue, nsmall = 4)
```

tau = 0の帰無仮説の元で、tau（平均値の差）の実現値が発生する確率は
1%であり、1%有意水準で帰無仮説は棄却される。
また、tauの絶対値の分布は以下のようになる。

```{r}
ggplot(tibble::tibble(t_distribution)) +
  geom_line(aes(x = abs(t_distribution)),
            stat = "density")
```











